# Interacting Species {#sppPro}

To build diagrams that accounts for the issues and nature of data collection as well as incorperating the life history constrains of the species being modelled.

```{r message=FALSE, warning=FALSE, include=FALSE}
library("dplyr")
library("knitr")
library("docxtools")
library("tufte")
library("DT")
library("flexdashboard")
library("plotly")
library("rbokeh")

source("./R/toc_gist.R")
#cite: devtools::source_gist("c83e078bf8c81b035e32c3fc0cf04ee8",  filename = 'render_toc.R')

#example
# load("./data/dat-rds-test.RData")
# datatable(iris)
# invalidate cache when the tufte version changes
# compareGroups::cGroupsGUI(mtcars)
#document global rules
knitr::opts_chunk$set(comment=NA,
                      fig.path = "../figs/",
                      echo=FALSE, 
                      fig.height=6, 
                      fig.width=10,
                      message=FALSE, 
                      warning=FALSE,tidy = FALSE
                      # , cache.extra = packageVersion('tufte')
                      )
# options(htmltools.dir.version = FALSE)

# how do I do this??
# ,eval = FALSE,include = FALSE

# export .r code only
# knitr::purl("./Davidson_2019_BeechForest.Rmd")

# render draft to webpage
# rmarkdown::render(input = "Davidson_2019_BeechForest.Rmd")
# ,
#                   output_format = "html_document",
#                   output_file = "Davidson_2019_t.html")

# formatR
# libraries needed
# source("./R/r-packages-needed.R", echo = FALSE)
# source("./R/theme_raw_fig3s.r", echo = FALSE)
# source("./R/davidson_2019_theme.r", echo = FALSE)

# adding info from old manuscript for now
# source("./R/manuscript-source-code.R", echo = FALSE)

## Table of Contents
```

```{r echo=FALSE} 
toc.files <- c("index.Rmd")
toc.gist(toc.files)
```

## Three species models {.tabset}

### v1

```{r}
grViz("
#add nodes
  digraph boxes_and_circles{
  node [shape = box]
  Seed; Density; Rats; Mice
#edge statements
edge [arrowhead = normal]
Seed->Mice
Density->Mice
Mice->Rats Rats->Mice
# Seed->Density
# Density->Rats
  }"
)
```

### v2

```{r}
grViz("
#add nodes
  digraph boxes_and_circles{
  node [shape = box]
  Seed; Density; Rats; Mice
#edge statements
edge [arrowhead = normal]
Seed->Mice
Density->Mice
Mice->Rats Rats->Mice
# Seed->Density
# Density->Rats
  }"
)
```
